Муллабаев Александр
urfu-2016/qa-task-03 pull request #22
Opened 2017-04-25 05:23 UTC by ProgrammerMaf

2017-05-03 12:34 UTC, mokhov requested changes
Нужны правки

2017-05-03 12:34 UTC, mokhov commented on getPokerHand.js
> +    return splitDice(dice, 4, dice => true);
Эта функция выполняется почти при каждой проверке – не оптимально

2017-05-03 12:34 UTC, mokhov commented on tests/getPokerHand-test.js
> +    describe('incorrectHand', () => {
Нет проверки на руку с неправильными значениями (<1 или >6)

2017-05-03 12:34 UTC, mokhov commented on tests/getPokerHand-test.js
> +        describe('pokerCombination', () => {
Можно ограничиться одним тестом на каждый случай

2017-05-10 10:33 UTC, ProgrammerMaf commented
Поправил замечания

2017-05-16 05:04 UTC, mokhov approved these changes

2017-05-16 05:04 UTC, closed without merging