Каширин Максим
urfu-2016/qa-task-03 pull request #29
Opened 2017-04-25 19:05 UTC by Vole1

2017-04-27 08:50 UTC, zmenka requested changes
Здорово, что решение разбито на подфункции, правда поиск комбинации сложноват.. По тестам все ок, небольшие недочеты

2017-04-27 08:50 UTC, zmenka commented on getPokerHand.js
> +        throw new Error('Функция принимает только 1 аргумент')
👍

2017-04-27 08:50 UTC, zmenka commented on getPokerHand.js
> +        if (!Number.isInteger(number) || number < 1 || number > 6)
Лучше разбить на 2 ошибки - проверка на число и проверка на диапазон. Так пользователю будет проще понять, что не так)

2017-04-27 08:50 UTC, zmenka commented on getPokerHand.js
> +        if (indexesOfEq[iterCounter] != undefined && indexesOfEq[iterCounter].length != 0)
А точно нужна проверка indexesOfEq[iterCounter].length != 0 ?

2017-04-27 08:50 UTC, zmenka commented on getPokerHand.js
> +    else if (repetitionsInds[1] == undefined || repetitionsInds[1].length == 0) {
Эта тоже нужна проверка? repetitionsInds[1].length == 0

2017-04-27 08:50 UTC, zmenka commented on tests/getPokerHand-test.js
> +    it ('should return `Фулл хаус` for [5, 1, 5, 5, 1]', () =>{
👍 Здорово, что нестандартные комбинации тестятся

2017-04-27 08:50 UTC, zmenka commented on tests/getPokerHand-test.js
> +    it ('should throw error when arguments number is bigger than 1', () =>{
👍

2017-04-27 08:50 UTC, zmenka commented on tests/getPokerHand-test.js
> +    	const actual = () => getPokerHand([1, 2.6, 3, 4, 5]);
👍 за нецелые числа

2017-04-27 08:50 UTC, zmenka commented on tests/getPokerHand-test.js
> +    it ('should throw error when array elements are not from {1, 2, 3, 4, 5, 6} set', () =>{
Думаю излишний тест

2017-04-27 08:50 UTC, zmenka commented on tests/getPokerHand-test.js
>      // Напишите тесты на ваш замечательный код здесь
Я бы еще над названиями тестов подумала. Часто они одинаковые и не описывают, какой конкретно кейс проверяется - "Кидает ошибку при числе меньше 1 "

2017-04-27 11:41 UTC, Vole1 commented on tests/getPokerHand-test.js
> +    it ('should throw error when array elements are not from {1, 2, 3, 4, 5, 6} set', () =>{
Почему?

2017-04-28 06:17 UTC, zmenka approved these changes
Принято! Все здорово

2017-04-28 13:02 UTC, closed without merging