Шеломов Никита
urfu-2016/qa-task-03 pull request #31
Opened 2017-04-26 06:15 UTC by NikShel

2017-04-27 06:14 UTC, Zhigalov requested changes
[Гернератор тестов](https://urfu-2016.github.io/testing-slides/06-mock/#/2/4) это ОК, но я бы остановился [на списке](https://urfu-2016.github.io/testing-slides/06-mock/#/2/3)

2017-04-27 06:14 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +        [[1,1,1,1,1], 'Покер'],
Для благозвучности `[[1,1,1,1,1], 'Покер']` -> `{ dice: [1,1,1,1,1], expected: 'Покер' }`

2017-04-27 06:14 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +        [{ a: 1 }, invalidDiceErrorRE],
Проверять что на вход ничего не подается - это тоже хорошая практика

2017-04-27 06:14 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +        [[1,2,3,4,6], invalidValuesErrorRE],
Шестёрка же допустима.
Вот семёрка не может выпасть на кубике

2017-04-27 06:14 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +    ];
Нет проверки на фейл при дробных значениях костей

2017-04-30 05:36 UTC, NikShel commented on tests/getPokerHand-test.js
> +        [[1,2,3,4,6], invalidValuesErrorRE],
Надо чаще в настолки играть :/

2017-04-30 05:56 UTC, NikShel commented
@Zhigalov поправил

2017-05-02 05:53 UTC, Zhigalov approved these changes

2017-05-02 05:53 UTC, Zhigalov commented
💯

2017-05-02 05:53 UTC, closed without merging